[project]
name = "pdf-transcriber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.57.1",
    "openai>=1.95.1",
    "pymupdf>=1.26.3",
    "python-dotenv>=1.1.1",
]
